smartcontract/urls.py
from django.conf.urls import url
from . import views

app_name = 'smartcontract'

urlpatterns = [
    url(r'^product/$', views.product_list, name="list"),
    url(r'^product/create/$', views.product_new, name="create"),
    url(r'^product/(?P<id>[\w-]+)/$', views.product_disp, name="disp"),
    url(r'^product/transfer/(?P<id>[\w-]+)/$', views.change_owner, name="transfer"),
]

veribuy/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from smartcontract import views

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^admin/', admin.site.urls),
    url(r'^smartcontract/', include('smartcontract.urls')),
    url(r'^accounts/', include('accounts.urls')),
    # url(r'^$', views.product_list, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smartcontract/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    manufacturer  = models.ForeignKey(User, blank=False, on_delete=models.CASCADE, related_name='manufacturer') 
    retailer  = models.ForeignKey(User, blank=False, on_delete=models.CASCADE, related_name='retailer')
    owner  = models.ForeignKey(User, blank=False, on_delete=models.CASCADE, related_name='owner') 
    name = models.CharField(max_length=50)
    desc = models.TextField()
    # slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

smartcontract/forms.py
from django import forms
from . import models

class ProductForm(forms.ModelForm):
    class Meta:
        model = models.Product
        fields = ['name', 'desc', 'retailer']

class EditOwnerForm(forms.ModelForm):
    class Meta:
        model = models.Product
        fields = ['owner']

smartcontract/views.py
from django.shortcuts import render, redirect
from .models import Product
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from . import forms

import json
from web3 import Web3

ganache_url = "http://127.0.0.1:7545"
web3 = Web3(Web3.HTTPProvider(ganache_url))

web3.eth.defaultAccount = web3.eth.accounts[0]

abi = json.loads('[{"inputs":[{"internalType":"uint256","name":"_pID","type":"uint256"},{"internalType":"uint256","name":"_uID","type":"uint256"}],"name":"change_owner","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"string","name":"_name","type":"string"},{"internalType":"string","name":"_desc","type":"string"},{"internalType":"uint256","name":"_mID","type":"uint256"},{"internalType":"uint256","name":"_rID","type":"uint256"},{"internalType":"uint256","name":"_oID","type":"uint256"}],"name":"create_product","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"string","name":"_username","type":"string"}],"name":"create_user","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"payable","type":"function"},{"inputs":[],"name":"get_products_count","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"get_users_count","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"productArr","outputs":[{"internalType":"uint256","name":"id","type":"uint256"},{"internalType":"string","name":"name","type":"string"},{"internalType":"string","name":"description","type":"string"},{"internalType":"uint256","name":"manufactuerID","type":"uint256"},{"internalType":"uint256","name":"retailerID","type":"uint256"},{"internalType":"uint256","name":"ownerID","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"userArr","outputs":[{"internalType":"uint256","name":"id","type":"uint256"},{"internalType":"string","name":"username","type":"string"}],"stateMutability":"view","type":"function"}]')
address = web3.toChecksumAddress("0x83bad3BAe42a184724D05CeB9636dE152fc5753e")

contract = web3.eth.contract(address=address, abi=abi)

# Create your views here.

def home(request):
    return render(request, 'smartcontract/index.html')

def product_list(request):
    products = get_products_frm_contract()
    for product in products:
        for i in range(3,6):
            product[i] = contract.functions.userArr(product[i]).call()[1]
    return render(request, 'smartcontract/product_list.html', {'products':products})

def get_products_frm_contract():
    func_to_call = 'get_products_count'
    contract_func = contract.functions[func_to_call]
    product_count = contract_func().call()

    products = []
    for i in range(product_count):
        product = contract.functions.productArr(i+1).call()
        products.append(product)
    return products

def product_disp(request, id):
    product = contract.functions.productArr(int(id)).call()
    for i in range(3,6):
        product[i] = contract.functions.userArr(product[i]).call()[1]
    return render(request, 'smartcontract/product_display.html', {'product':product})

@csrf_exempt
@login_required(login_url="/accounts/login/")
def product_new(request):
    if request.method == 'POST':
        form = forms.ProductForm(request.POST)
        if form.is_valid():
            tx_hash = contract.functions.create_product(form.cleaned_data["name"], form.cleaned_data["desc"], request.user.id, form.cleaned_data["retailer"].id, form.cleaned_data["retailer"].id).transact()
            web3.eth.waitForTransactionReceipt(tx_hash)
            return redirect('smartcontract:list')
    else:
        form = forms.ProductForm
    return render(request, 'smartcontract/product_create.html', {'form':form})

@csrf_exempt
@login_required(login_url="/accounts/login/")
def change_owner(request, id):
    if request.method == "POST":
        form = forms.EditOwnerForm(request.POST)
        if form.is_valid():
            tx_hash = contract.functions.change_owner(int(id),form.cleaned_data["owner"].id).transact()
            web3.eth.waitForTransactionReceipt(tx_hash)
            return redirect('smartcontract:list')
    else:
        product = contract.functions.productArr(int(id)).call()
        for i in range(3,6):
            product[i] = contract.functions.userArr(product[i]).call()[1]
        form = forms.EditOwnerForm()
        return render(
            request, "smartcontract/transfer_ownership.html", {'form':form, 'product': product}
        )

smartcontract/templates/smartcontract/product_create.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<style type="text/css">
		* {box-sizing: border-box}

/* Add padding to containers */
.container {
  padding: 16px;
}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Overwrite default styles of hr */
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Set a style for the submit/register button */
.registerbtn {
  background-color: #602FDA;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.registerbtn:hover {
  opacity:1;
}

/* Add a blue text color to links */
a {
  color: dodgerblue;
}

/* Set a grey background color and center the text of the "sign in" section */
.signin {
  background-color: #f1f1f1;
  text-align: center;
}

	</style>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <meta name="description" content="Mobile Application HTML5 Template">

  <meta name="copyright" content="MACode ID, https://www.macodeid.com/">

  <title>Mobster - One page app template</title>

  <link rel="shortcut icon" href='{% static "/favicon.png" %}' type="image/x-icon">

  <link rel="stylesheet" href='{% static "/css/maicons.css" %}'>

  <link rel="stylesheet" href='{% static "/vendor/animate/animate.css" %}'>

  <link rel="stylesheet" href='{% static "/vendor/owl-carousel/css/owl.carousel.min.css" %}'>

  <link rel="stylesheet" href='{% static "/css/bootstrap.css" %}'>

  <link rel="stylesheet" href='{% static "/css/mobster.css" %}'>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark navbar-floating">
  <div class="container">
    <a class="navbar-brand" href='../index'>
      <img src='{% static "/favicon-light.png" %}' alt="" width="40">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarToggler">
      <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/smartcontract/product/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/smartcontract/product/create/">Create new product</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="/accounts/logout">Log Out</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<main class="bg-light">

<div class="page-hero-section bg-image hero-mini" style="background-image: url('{% static "/img/hero_mini.svg" %}');">
  <div class="hero-caption">
    <div class="container fg-white h-100">
      <div class="row justify-content-center align-items-center text-center h-100">
        <div class="col-lg-6">
          <h3 class="mb-4 fw-medium">Create New Product</h3>
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb breadcrumb-dark justify-content-center bg-transparent">
              <li class="breadcrumb-item"><a href="../index">Home</a></li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="page-section pt-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card-page">
          <h4  style="text-align: center;" class="fg-primary">Add Product Details</h4>
          <hr>

<!--<form action="action_page.php">
  <div class="container">
    
    <label for="name"><b>Name</b></label>
    <input type="text" placeholder="Enter name" name="name" id="name" required>

    <label for="email"><b>Email</b></label>
    <input type="text" placeholder="Enter Email" name="email" id="email" required>

    <label for="address"><b>Address</b></label>
    <input type="text" placeholder="Enter address" name="address" id="address">

    <label for="product"><b>Product</b></label>
    <input type="text" placeholder="Enter product" name="product" id="product" required>

    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" id="psw" required>

    <label for="psw-repeat"><b>Repeat Password</b></label>
    <input type="password" placeholder="Repeat Password" name="psw-repeat" id="psw-repeat" required>
    <hr>

    <p>By creating an account you agree to our <a href="#">Terms & Privacy</a>.</p>
    <button type="submit" class="registerbtn">Register</button>
  </div>

  
</form>-->

<div class="create_product">
 
  <form class="product_create" action="{% url 'smartcontract:create' %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Add Product">
  </form>
</div>

          
        </div>
        
        
      </div>
    </div>
  </div>
</div>

</main> <!-- .bg-light -->


<div class="page-footer-section bg-dark fg-white">

  <hr>

  <div class="container">
    <div class="row">
      <div class="col-12 col-md-6 py-2">
        <img src='{% static "/favicon-light.png" %}' alt="" width="40">
        <!-- Please don't remove or modify the credits below -->
        <p class="d-inline-block ml-2">Copyright &copy; <a href="https://www.macodeid.com/" class="fg-white fw-medium">MACode ID</a>. All rights reserved</p>
      </div>
      <div class="col-12 col-md-6 py-2">
        <ul class="nav justify-content-end">
          <li class="nav-item"><a href="#" class="nav-link">Terms of Use</a></li>
          <li class="nav-item"><a href="#" class="nav-link">Privacy Policy</a></li>
          <li class="nav-item"><a href="#" class="nav-link">Cookie Policy</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<script src='{% static "/js/jquery-3.5.1.min.js" %}'></script>

<script src='{% static "/js/bootstrap.bundle.min.js" %}'></script>

<script src='{% static "/vendor/owl-carousel/js/owl.carousel.min.js" %}'></script>

<script src='{% static "/vendor/wow/wow.min.js" %}'></script>

<script src='{% static "/js/mobster.js" %}'></script>

</body>
</html>

smartcontract/templates/smartcontract/product_display.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<style type="text/css">
		* {box-sizing: border-box}

/* Add padding to containers */
.container {
  padding: 16px;
}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Overwrite default styles of hr */
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Set a style for the submit/register button */
.registerbtn {
  background-color: #602FDA;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.registerbtn:hover {
  opacity:1;
}

/* Add a blue text color to links */
a {
  color: dodgerblue;
}

/* Set a grey background color and center the text of the "sign in" section */
.signin {
  background-color: #f1f1f1;
  text-align: center;
}

	</style>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <meta name="description" content="Mobile Application HTML5 Template">

  <meta name="copyright" content="MACode ID, https://www.macodeid.com/">

  <title>Product Display</title>

  <link rel="shortcut icon" href='{% static "/favicon.png" %}' type="image/x-icon">

  <link rel="stylesheet" href='{% static "/css/maicons.css" %}'>

  <link rel="stylesheet" href='{% static "/vendor/animate/animate.css" %}'>

  <link rel="stylesheet" href='{% static "/vendor/owl-carousel/css/owl.carousel.min.css" %}'>

  <link rel="stylesheet" href='{% static "/css/bootstrap.css" %}'>

  <link rel="stylesheet" href='{% static "/css/mobster.css" %}'>

  </head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark navbar-floating">
  <div class="container">
    <a class="navbar-brand" href="../index">
      <img src='{% static "/favicon-light.png" %}' alt="" width="40">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarToggler">
      <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/smartcontract/product/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/smartcontract/product/create/">Create new product</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="/accounts/logout">Log Out</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<main class="bg-light">

<div class="page-hero-section bg-image hero-mini" style="background-image: url('{% static "/img/hero_mini.svg" %}');">
  <div class="hero-caption">
    <div class="container fg-white h-100">
      <div class="row justify-content-center align-items-center text-center h-100">
        <div class="col-lg-6">
          <h3 class="mb-4 fw-medium">Product Display</h3>
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb breadcrumb-dark justify-content-center bg-transparent">
              <li class="breadcrumb-item"><a href="../index">Home</a></li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="page-section pt-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card-page">
          <h4  style="text-align: center;" class="fg-primary">Product Details</h4>
          <hr>

<div class="container">
  <div class="product-disp">
    <div class="product">
        <!--<h2>Product Details:</h2>-->
        <h3>Product: {{ product.1 }}</h3>
        <h5>Description: {{ product.2 }}</h5>
        <p>Manufactured By: {{ product.3 }}</p>
        <p>Retailer: {{ product.4 }}</p>
        <p>Current Owner: {{ product.5 }}</p>
        {% ifequal request.user.username product.5 %}
            <a href="{% url 'smartcontract:transfer' id=product.0 %}"><input type="button" value="Transfer Ownership"></a>
        {% endifequal %}
    </div>
</div>
</div>

          
        </div>
        
        
      </div>
    </div>
  </div>
</div>

</main> <!-- .bg-light -->


<div class="page-footer-section bg-dark fg-white">

  <hr>

  <div class="container">
    <div class="row">
      <div class="col-12 col-md-6 py-2">
        <img src='{% static "/favicon-light.png" %}' alt="" width="40">
        <!-- Please don't remove or modify the credits below -->
        <p class="d-inline-block ml-2">Copyright &copy; <a href="https://www.macodeid.com/" class="fg-white fw-medium">MACode ID</a>. All rights reserved</p>
      </div>
      <div class="col-12 col-md-6 py-2">
        <ul class="nav justify-content-end">
          <li class="nav-item"><a href="#" class="nav-link">Terms of Use</a></li>
          <li class="nav-item"><a href="#" class="nav-link">Privacy Policy</a></li>
          <li class="nav-item"><a href="#" class="nav-link">Cookie Policy</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<script src='{% static "/js/jquery-3.5.1.min.js" %}'></script>

<script src='{% static "/js/bootstrap.bundle.min.js" %}'></script>

<script src='{% static "/vendor/owl-carousel/js/owl.carousel.min.js" %}'></script>

<script src='{% static "/vendor/wow/wow.min.js" %}'></script>

<script src='{% static "/js/mobster.js" %}'></script>

</body>
</html>

smartcontract/templates/smartcontract/product_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<style type="text/css">
		* {box-sizing: border-box}

/* Add padding to containers */
.container {
  padding: 16px;
}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Overwrite default styles of hr */
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Set a style for the submit/register button */
.registerbtn {
  background-color: #602FDA;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.registerbtn:hover {
  opacity:1;
}

/* Add a blue text color to links */
a {
  color: dodgerblue;
}

/* Set a grey background color and center the text of the "sign in" section */
.signin {
  background-color: #f1f1f1;
  text-align: center;
}

	</style>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <meta name="description" content="Mobile Application HTML5 Template">

  <meta name="copyright" content="MACode ID, https://www.macodeid.com/">

  <title>Product List</title>

  <link rel="shortcut icon" href='{% static "/favicon.png" %}' type="image/x-icon">

  <link rel="stylesheet" href='{% static "/css/maicons.css" %}'>

  <link rel="stylesheet" href='{% static "/vendor/animate/animate.css" %}'>

  <link rel="stylesheet" href='{% static "/vendor/owl-carousel/css/owl.carousel.min.css" %}'>

  <link rel="stylesheet" href='{% static "/css/bootstrap.css" %}'>

  <link rel="stylesheet" href='{% static "/css/mobster.css" %}'>
 </head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark navbar-floating">
  <div class="container">
    <a class="navbar-brand" href="../index">
      <img src='{% static "/favicon-light.png" %}' alt="" width="40">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarToggler">
      <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/smartcontract/product/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/smartcontract/product/create/">Create new product</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="/accounts/logout">Log Out</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<main class="bg-light">

<div class="page-hero-section bg-image hero-mini" style="background-image: url('{% static "/img/hero_mini.svg" %}');">
  <div class="hero-caption">
    <div class="container fg-white h-100">
      <div class="row justify-content-center align-items-center text-center h-100">
        <div class="col-lg-6">
          <h3 class="mb-4 fw-medium">Product List</h3>
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb breadcrumb-dark justify-content-center bg-transparent">
              <li class="breadcrumb-item"><a href="../index">Home</a></li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="page-section pt-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card-page">
          <h4  style="text-align: center;" class="fg-primary">The following is the list of all the products</h4>
          <hr>

<div class="container">
<!--<h1>The following is the list of all the products:</h1>-->
    <div class="products">
        {% for product in products %}
            <h2><a href="{% url 'smartcontract:disp' id=product.0 %}">{{ product.1 }}</a></h2>
            <p>Description: {{ product.2 }}</p>
            <p>Current Owner: {{ product.5 }}</p>
        {% endfor %}
    </div>
    </div>

          
        </div>
        
        
      </div>
    </div>
  </div>
</div>

</main> <!-- .bg-light -->


<div class="page-footer-section bg-dark fg-white">

  <hr>

  <div class="container">
    <div class="row">
      <div class="col-12 col-md-6 py-2">
        <img src='{% static "/favicon-light.png" %}' alt="" width="40">
        <!-- Please don't remove or modify the credits below -->
        <p class="d-inline-block ml-2">Copyright &copy; <a href="https://www.macodeid.com/" class="fg-white fw-medium">MACode ID</a>. All rights reserved</p>
      </div>
      <div class="col-12 col-md-6 py-2">
        <ul class="nav justify-content-end">
          <li class="nav-item"><a href="#" class="nav-link">Terms of Use</a></li>
          <li class="nav-item"><a href="#" class="nav-link">Privacy Policy</a></li>
          <li class="nav-item"><a href="#" class="nav-link">Cookie Policy</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<script src='{% static "/js/jquery-3.5.1.min.js" %}'></script>

<script src='{% static "/js/bootstrap.bundle.min.js" %}'></script>

<script src='{% static "/vendor/owl-carousel/js/owl.carousel.min.js" %}'></script>

<script src='{% static "/vendor/wow/wow.min.js" %}'></script>

<script src='{% static "/js/mobster.js" %}'></script>

</body>
</html>